name: WordPal
options:
  bundleIdPrefix: com.rayren
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
targets:
  WordPal:
    type: application
    platform: iOS
    sources:
      - WordPal
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rayren.wordpal
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: Wordmate
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: QQ3446GC5P
